### ISSUE TITLE
exe not opened

### ISSUE THREAD

**Issue by yaffid** [Mecogumi/Live2D-Crack#2]
i cant open the exe i already put file on root live2d but still not open and i try the java "cannot find javaw..." 
help

**Comment by yaffid** [comment]
> i cant open the exe i already put file on root live2d but still not open and i try the java "cannot find javaw..." help

**Comment by Mecogumi** [comment]
Can u send a screenshoot of ur live2D root folder?

**Comment by yaffid** [comment]
![image](https://github.com/Mecogumi/Live2D-Crack/assets/173092880/1d481c20-bf5b-4f15-b21c-dee9e2f75f5a)
fixed ! i rename the rlm1501 to _mod.jar and rename it on bat files too and its work
