### ISSUE TITLE
Double-clicking the .exe file/opening as an administrator does not respond, but it will open the .rar folder.

### ISSUE THREAD

**Issue by bingermaomao** [Mecogumi/Live2D-Crack#3]
![Crack question 00_00_00-00_00_30](https://github.com/Mecogumi/Live2D-Crack/assets/131090738/ceef7e4a-3610-42cf-9be1-1ccfd4ff3ef3)

Thank you for sharing, but I encountered a problem. I am using Live2d version 5.0.06, and I recorded a video and uploaded it for easier troubleshooting. I have turned off the antivirus software, but it still won’t open properly.

**Comment by Mecogumi** [comment]
You need to extract the files "Live2D-AutoCrack.exe" and "rlm1501.jar" from the zip file you are opening, and place those files in the root directory of live2d as I show in the attached image, after doing that you must run "Live2D- AutoCrack.exe" and follow the instructions in the GitHub Readme.MD
![image](https://github.com/Mecogumi/Live2D-Crack/assets/70516015/016383f1-dcc3-480a-a29f-e93ccf3f2542)

**Comment by bingermaomao** [comment]
Yes, as shown in the image. I did put both files in the root directory, but there is no response when I double-click them. Maybe it’s a problem with my computer, I don’t know how to solve it.

![problem](https://github.com/Mecogumi/Live2D-Crack/assets/131090738/8b7b7e7b-1e4b-4b2c-8e0e-21684987ca11)

**Comment by bingermaomao** [comment]
I followed the steps: first, I opened Live2D and then closed it; second, I clicked on the crack file. However, there is no response after double-clicking the crack file, and it also doesn’t work when I right-click and run as an administrator.  :'(

My English is not good, so I used a translation tool. I’m not sure if I was clear, but thank you for reading my message and replying.^^

**Comment by bingermaomao** [comment]
> You need to extract the files "Live2D-AutoCrack.exe" and "rlm1501.jar" from the zip file you are opening, and place those files in the root directory of live2d as I show in the attached image, after doing that you must run "Live2D- AutoCrack.exe" and follow the instructions in the GitHub Readme.MD ![image](https://private-user-images.githubusercontent.com/70516015/340452925-016383f1-dcc3-480a-a29f-e93ccf3f2542.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTg2NjM1NTYsIm5iZiI6MTcxODY2MzI1NiwicGF0aCI6Ii83MDUxNjAxNS8zNDA0NTI5MjUtMDE2MzgzZjEtZGNjMy00ODBhLWEyOWYtZTkzY2NmM2YyNTQyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MTclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjE3VDIyMjczNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTljZWU2MDQ3OGFjNmU2NmVjZTRmYTEwNWMwMjliOGFiNzRmYmE1MjlkZDdlMDQyZmVjODMzYWVjMTVjZGI3ZTMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.-Iabn6_WqIPtkoLSp8Pf8Gixr9oNB7QtlFgS0B3Zm2Y)

I followed the steps: first, I opened Live2D and then closed it; second, I clicked on the crack file. However, there is no response after double-clicking the crack file, and it also doesn’t work when I right-click and run as an administrator. :'(

My English is not good, so I used a translation tool. I’m not sure if I was clear, but thank you for reading my message and replying.^^

**Comment by Mecogumi** [comment]
In the video, the file that you are trying to open and that is in the root directory is a .zip, not an .exe and inside the zip that you opened, there is the .exe that should be in the root directory, I attach a screenshot with an arrow your video, that file "Live2D-AutoCrack.EXE" is the one that should be in the root directory of live2D, not the ZIP
![chrome_seVNwenlSU](https://github.com/Mecogumi/Live2D-Crack/assets/70516015/18a29951-6a87-4579-ad6b-aa62e55ad4a0)


What can help you understand the difference between the files may be the "File name extensions" option, I have attached an image of where that option is located, although the image is in Spanish, the options are found in the same place no matter the language, you open the "file explorer", go to the "view" tab and on the right you should find the option "File name extensions" or similar, activate this box
![image](https://github.com/Mecogumi/Live2D-Crack/assets/70516015/dd99e4c2-83fb-448e-a100-45e7f30d0bfd)

**Comment by bingermaomao** [comment]
> In the video, the file that you are trying to open and that is in the root directory is a .zip, not an .exe and inside the zip that you opened, there is the .exe that should be in the root directory, I attach a screenshot with an arrow your video, that file "Live2D-AutoCrack.EXE" is the one that should be in the root directory of live2D, not the ZIP ![chrome_seVNwenlSU](https://private-user-images.githubusercontent.com/70516015/340470390-18a29951-6a87-4579-ad6b-aa62e55ad4a0.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTg2NjQwMjMsIm5iZiI6MTcxODY2MzcyMywicGF0aCI6Ii83MDUxNjAxNS8zNDA0NzAzOTAtMThhMjk5NTEtNmE4Ny00NTc5LWFkNmItYWE2MmU1NWFkNGEwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MTclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjE3VDIyMzUyM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTMzMzkyYTViNWJlZGNmZGEyYzVmZTBjMjMxZTk1ZTgxMDUxMzc3Y2Q3M2Q5ZTQ3NmViMzQ0ZDI0MDUwZGNjOGQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.sccEPmPNQeMEZRk4DrQlu0Kao6H2R9wxMTPPnMiH2SM)
> 
> What can help you understand the difference between the files may be the "File name extensions" option, I have attached two images of where that option is located, although the image is in Spanish, the options are found in the same place no matter the language, you open the "file explorer", go to the "view" tab and on the right you should find the option "File name extensions" or similar, activate this box ![image](https://private-user-images.githubusercontent.com/70516015/340470837-dd99e4c2-83fb-448e-a100-45e7f30d0bfd.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTg2NjQwMjMsIm5iZiI6MTcxODY2MzcyMywicGF0aCI6Ii83MDUxNjAxNS8zNDA0NzA4MzctZGQ5OWU0YzItODNmYi00NDhlLWExMDAtNDVlN2YzMGQwYmZkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MTclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjE3VDIyMzUyM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTE2NjJkMDc2Njc3NGFlODEyNjVhZTU5NDIzYTQ2YTFlZmY1ZGQxZmIzNTc3ODQ0YmI4MjU1ZjVkYmZlOTZhNTMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.sodaddr1zFmHgus4R-hw3er_NkF8TFhIUQbXa7qYxIg) or ![image](https://private-user-images.githubusercontent.com/70516015/340471660-d1823796-59a6-4580-a2c0-2ebe793eb690.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTg2NjQwMjMsIm5iZiI6MTcxODY2MzcyMywicGF0aCI6Ii83MDUxNjAxNS8zNDA0NzE2NjAtZDE4MjM3OTYtNTlhNi00NTgwLWEyYzAtMmViZTc5M2ViNjkwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MTclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjE3VDIyMzUyM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTYwNWMxZTcwZmNiNDdlNmQ1OWNkMjY2NjFkZWQwZmYyZjQ2MTljNmVmMDI2NTA2NTFjZmY2YTFmYjBlM2M2YjImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.0GQgbG31mpMC42NRbO6xqDb0H1MMSebYd1VsItlSqpA)

Thank you for teaching me how to open file extensions.

I’m quite sure that I opened the .exe file. In the video, I want to express that when I have the .rar file open and I double-click to run the .exe file, it does not open the crack window, but instead, it pops up the .rar page. If I close the .rar file, there is no response at all, and the crack window does not open.

On the image, it’s labeled with 'Live2D-AutoCrack.exe', 'rlm1501.jar', and '.rar' three files.

![QQ截图20240618065455](https://github.com/Mecogumi/Live2D-Crack/assets/131090738/c0db94fd-0ebe-40aa-a151-88bb7bd1e76f)

**Comment by bingermaomao** [comment]
I think the crack file that is supposed to run might be blocked by some software on my computer, but I’m not sure about the reason.

**Comment by Mecogumi** [comment]
I'm not really sure why the file doesn't run correctly on your computer, but you can try using the java version, the only requirement is to have java installed

**Comment by bingermaomao** [comment]
Thank you very much!！！！
 It seems like I’ve succeeded with the Java method! And here is the attached image.❤

Although I encountered another problem during this time, and I’m unable to describe the details to you in English, after looking up solutions, I was able to solve it step by step. I’m very happy and grateful for the internet, for Gub, and for you!❀

![QQ截图20240618082237](https://github.com/Mecogumi/Live2D-Crack/assets/131090738/8cebc0f3-fa7a-4b8b-b3fa-782a765a7609)

**Comment by bingermaomao** [comment]
> I'm not really sure why the file doesn't run correctly on your computer, but you can try using the java version, the only requirement is to have java installed, and unlike the exe it is not necessary to have it in the root directory

Thank you, I think I succeeded!^ ^~

**Comment by Mecogumi** [comment]
On the contrary, thanks to you for giving me the opportunity to try to solve it, I think that using Java as the main language of this program was a bad decision, perhaps in future versions I will decide to change to a language that does not generate so many problems when generating a .exe
